### PR TITLE
fixes: Pro config options not parsed properly

### LINKED ISSUE #18: Juicebox Pro Options Config
fkelly: I see the dots you are suggesting can be configured for thumbnails. They are on the Juicebox Lite config screen, not on the pro one. I guess we need to do both configuration options and they are cumulative?

Juicebox Pro options are configured in the different way.
You can define them in ' Juicebox Library - Pro / Manual Config' textfield.
Available options (lite/pro) are listed here http://www.juicebox.net/support/config_options

So I don't think we need to take care about this. Just test it as it works as designed.
Seems there's no other way of settings Pro options at the current Juicebox version. Only that textfield.

### PR DESCRIPTION
**Pull request by D4KO**
The regression was introduced with previous changes (commit #b72b6e9) concerning coding standards.

https://git.drupalcode.org/project/juicebox/-/blob/8.x-2.x/src/JuiceboxFormatter.php line 395

list($full_match, $name, $value) = $matches;
was changed to
list($name, $value) = $matches;
to prevent 'Unused variable $full_match '...
This change breaks parsing of manual Pro config options due to missing param in list command.
https://www.php.net/manual/en/function.list.php

We should definitely review all commits concerning list command to fix other potential regressions we didn't noticed until now.

### CODE REVIEW

File: src/JuiceboxFormatter.php [hunk 1]
```diff
@@ -452,7 +452,7 @@ protected function setGalleryOptions(JuiceboxGalleryInterface $gallery, array $s
           // values.
           $matches = [];
           preg_match('/^([A-Za-z0-9]+?)="([^"]+?)"$/u', $option, $matches);
-          list($name, $value) = $matches;
+          list(, $name, $value) = $matches;
```
Comment (D4KO) [inline src/JuiceboxFormatter.php:455]: Current dev version (https://git.drupalcode.org/project/juicebox/-/blob/8.x-2.x/src/JuiceboxFormatter.php line: 395):
list($full_match, $name, $value) = $matches;
Needs coding standards review.

**Comment by fkelly12054** [comment]
I will run a full coding standards review, both the base and the DrupalStandards one, in the next day or two.  I'll post the results and we can make sure there are no further regressions.
